In [1]:
# importing libraries 
import numpy as np 
import pandas as pd 
import math 
import random 
#import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Initilization of 
# Data set

# defining the columns using normal distribution 
# np.random.randint(0, 2, 5) --> To produces 5 numbers. Each no is either 0 or 1 
# column 1  Symptom-I
cold = np.zeros((119711,), dtype=int)
# column 2  Symptom2
cough = np.zeros((119711,), dtype=int)
# column 3 Symptom3
feaver = np.zeros((119711,), dtype=int)
# column 4 Symptom4
breating = np.zeros((119711,), dtype=int)
# Column 5 Symptom 5
cronic = np.zeros((119711,), dtype=int)
# Column 6 
age = np.zeros((119711,), dtype=int) #
#Column 7 The output either Covid-19 or NON-Covid
#disease = np.random.randint(1, 10, 500)
disease = np.zeros(119711, dtype='int')

In [4]:
#General Symptoms(GS) are 321. It is multiplied with 7. Hence, 321*7=2247
b=0
for i in range(0,2247):  #This is to fill General Symptoms  (GS-->1 in disease column)
    b=b+1
    if(b==1):
        cold[i]=0
        cough[i]=0
        feaver[i]=1
        breating[i]=0
        cronic[i]=0
        age[i]=0
        disease[i]=1
    if(b==2):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=0
        cronic[i]=0
        age[i]=0
        disease[i]=1
    if(b==3):
        cold[i]=0
        cough[i]=1
        feaver[i]=1
        breating[i]=0
        cronic[i]=0
        age[i]=0
        disease[i]=1
    if(b==4):
        cold[i]=1
        cough[i]=0
        feaver[i]=0
        breating[i]=0
        cronic[i]=0
        age[i]=0
        disease[i]=1
    if(b==5):
        cold[i]=1
        cough[i]=0
        feaver[i]=1
        breating[i]=0
        cronic[i]=0
        age[i]=0
        disease[i]=1
    if(b==6):
        cold[i]=1
        cough[i]=1
        feaver[i]=0
        breating[i]=0
        cronic[i]=0
        age[i]=0
        disease[i]=1
    if(b==7):
        cold[i]=1
        cough[i]=1
        feaver[i]=1
        breating[i]=0
        cronic[i]=0
        age[i]=0
        disease[i]=1
    if(b==7):
        b=1
    

In [5]:
# HR1 is 116. It is multiplied with 16. Hence, 116*16=1856. It is from 2247+1856=4103
b=0
for i in range(2247,4103):  #This is to fill   (HR1-->2 in disease column) or Low Risk
    b=b+1
    if(b==1):
        cold[i]=0
        cough[i]=0
        feaver[i]=0
        breating[i]=1
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==2):
        cold[i]=0
        cough[i]=0
        feaver[i]=1
        breating[i]=0
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==3):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=1
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==4):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=0
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==5):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=1
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==6):
        cold[i]=0
        cough[i]=1
        feaver[i]=1
        breating[i]=0
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==7):
        cold[i]=0
        cough[i]=1
        feaver[i]=1
        breating[i]=1
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==8):
        cold[i]=1
        cough[i]=0
        feaver[i]=0
        breating[i]=0
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==9):
        cold[i]=1
        cough[i]=0
        feaver[i]=0
        breating[i]=1
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==10):
        cold[i]=1
        cough[i]=0
        feaver[i]=1
        breating[i]=0
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==11):
        cold[i]=1
        cough[i]=0
        feaver[i]=1
        breating[i]=1
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==12):
        cold[i]=1
        cough[i]=1
        feaver[i]=0
        breating[i]=0
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==13):
        cold[i]=1
        cough[i]=1
        feaver[i]=0
        breating[i]=1
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==14):
        cold[i]=1
        cough[i]=1
        feaver[i]=1
        breating[i]=0
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==15):
        cold[i]=1
        cough[i]=1
        feaver[i]=1
        breating[i]=1
        cronic[i]=0
        age[i]=1
        disease[i]=2
    if(b==15):
        b=1
    

In [6]:
# HR2 is 67. It is multiplied with 16. Hence, 67*16=1072. It is from 4103+1072=5175
b=0
for i in range(4103,5175):  #This is to fill   (HR2-->3 in disease column) or Medium Risk
    b=b+1
    if(b==1):
        cold[i]=0
        cough[i]=0
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==2):
        cold[i]=0
        cough[i]=0
        feaver[i]=1
        breating[i]=0
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==3):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==4):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=0
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==5):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==6):
        cold[i]=0
        cough[i]=1
        feaver[i]=1
        breating[i]=0
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==7):
        cold[i]=0
        cough[i]=1
        feaver[i]=1
        breating[i]=1
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==8):
        cold[i]=1
        cough[i]=0
        feaver[i]=0
        breating[i]=0
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==9):
        cold[i]=1
        cough[i]=0
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==10):
        cold[i]=1
        cough[i]=0
        feaver[i]=1
        breating[i]=0
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==11):
        cold[i]=1
        cough[i]=0
        feaver[i]=1
        breating[i]=1
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==12):
        cold[i]=1
        cough[i]=1
        feaver[i]=0
        breating[i]=0
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==13):
        cold[i]=1
        cough[i]=1
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==14):
        cold[i]=1
        cough[i]=1
        feaver[i]=1
        breating[i]=0
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==15):
        cold[i]=1
        cough[i]=1
        feaver[i]=1
        breating[i]=1
        cronic[i]=1
        age[i]=0
        disease[i]=3
    if(b==15):
        b=1


In [7]:
# HR3 is 77. It is multiplied with 16. Hence, 77*16=1232. It is from 5175+1232=6407
b=0
for i in range(5175,6407):  #This is to fill   (HR3-->4 in disease column)
    b=b+1
    if(b==1):
        cold[i]=0
        cough[i]=0
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==2):
        cold[i]=0
        cough[i]=0
        feaver[i]=1
        breating[i]=0
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==3):
        cold[i]=0
        cough[i]=0
        feaver[i]=1
        breating[i]=1
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==4):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=0
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==5):
        cold[i]=0
        cough[i]=1
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==6):
        cold[i]=0
        cough[i]=1
        feaver[i]=1
        breating[i]=0
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==7):
        cold[i]=0
        cough[i]=1
        feaver[i]=1
        breating[i]=1
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==8):
        cold[i]=1
        cough[i]=0
        feaver[i]=0
        breating[i]=0
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==9):
        cold[i]=1
        cough[i]=0
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==10):
        cold[i]=1
        cough[i]=0
        feaver[i]=1
        breating[i]=0
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==11):
        cold[i]=1
        cough[i]=0
        feaver[i]=1
        breating[i]=1
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==12):
        cold[i]=1
        cough[i]=1
        feaver[i]=0
        breating[i]=0
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==13):
        cold[i]=1
        cough[i]=1
        feaver[i]=0
        breating[i]=1
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==14):
        cold[i]=1
        cough[i]=1
        feaver[i]=1
        breating[i]=0
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==15):
        cold[i]=1
        cough[i]=1
        feaver[i]=1
        breating[i]=1
        cronic[i]=1
        age[i]=1
        disease[i]=4
    if(b==15):
        b=1
    

In [8]:
#x.head()
data = pd.DataFrame()
data['cold']=cold
data['cough']=cough
data['feaver']=feaver
data['breating']=breating
data['cronic']=cronic
data['age']=age
data['disease']=disease
#data
#data.head()
    
#c=np.array(data.loc[3, ['cold', 'cough', 'feaver']])
#c.any()
#c.all()
data.to_csv('ds-covid-new34733-119711.csv', index=False, header=True)


In [9]:
df = pd.read_csv("ds-covid-new34733-119711.csv")
df.sample(5)

cold  cough  feaver  breating  cronic  age  disease
112545     0      0       0         0       0    0        0
95249      0      0       0         0       0    0        0
44447      0      0       0         0       0    0        0
113549     0      0       0         0       0    0        0
11021      0      0       0         0       0    0        0

# Accuracy of algorithms before balancing a dataset


Add corresponding code in below cells

In [10]:
df.disease.value_counts() #disease is a field name and it is dependent or output variable 

0    113304
1      2247
2      1856
4      1232
3      1072
Name: disease, dtype: int64

In [11]:
df.dtypes

cold        int64
cough       int64
feaver      int64
breating    int64
cronic      int64
age         int64
disease     int64
dtype: object

In [12]:
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix , classification_report
from tensorflow_addons import losses
from sklearn import metrics
from sklearn.metrics import accuracy_score, f1_score

In [13]:
X = df.drop('disease',axis='columns')
y = df['disease']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.5,random_state=0)

In [15]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train, y_train)
y_pred_lr=lr.predict(X_test)
scores=metrics.accuracy_score(y_test, y_pred_lr)
print(scores)
lr_cm1=confusion_matrix(y_test, y_pred_lr)
lr_cm1

0.9999832932371023


array([[56666,     0,     0,     0,     0],
       [    0,  1119,     0,     0,     0],
       [    0,     0,   938,     0,     0],
       [    1,     0,     0,   542,     0],
       [    0,     0,     0,     0,   590]], dtype=int64)

In [16]:
#from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import GaussianNB
naive=GaussianNB()
naive.fit(X_train, y_train)
naive_y_pred=naive.predict(X_test)
scores=metrics.accuracy_score(y_test, naive_y_pred)
print(scores)
naive_cm1=confusion_matrix(y_test, naive_y_pred)
naive_cm1

1.0


array([[56666,     0,     0,     0,     0],
       [    0,  1119,     0,     0,     0],
       [    0,     0,   938,     0,     0],
       [    0,     0,     0,   543,     0],
       [    0,     0,     0,     0,   590]], dtype=int64)

In [17]:
from sklearn.linear_model import SGDClassifier
sgd=SGDClassifier(loss='modified_huber',shuffle=True,random_state=101)
sgd.fit(X_train, y_train)
y_pred_sgd=sgd.predict(X_test)
scores=metrics.accuracy_score(y_test, y_pred_sgd)
print(scores)
sgd_cm1=confusion_matrix(y_test, y_pred_sgd)
sgd_cm1

1.0


array([[56666,     0,     0,     0,     0],
       [    0,  1119,     0,     0,     0],
       [    0,     0,   938,     0,     0],
       [    0,     0,     0,   543,     0],
       [    0,     0,     0,     0,   590]], dtype=int64)

In [18]:
#Code to find best K Value

#Importing KNN Classifier
from sklearn.neighbors import KNeighborsClassifier


# try K=1 through K=25 and record testing accuracy

#k_range = range(1, 26)

# We can create Python dictionary using [] or dict()
scores = []
k=5
# We use a loop through the range 1 to 26
# We append the scores in the dictionary

#for k in k_range:
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
scores.append(metrics.accuracy_score(y_test, y_pred))

print(scores)

[1.0]


In [19]:
# cold	cough	feaver	breating	cronic	age
print(knn.predict([[1,1,0,0,0,0]]))# Prediction of a person with some diseases.
#The output shows it is "1" Means GS,2 means HR1, 3 means HR2, and 4 means HR3.
print(knn.predict([[1,1,0,1,0,0]]))
print(knn.predict([[1,1,0,0,0,1]]))
print(knn.predict([[1,1,0,1,1,0]]))
print(knn.predict([[1,1,0,1,1,1]]))
print(knn.predict([[1,1,0,0,1,1]]))
print(knn.predict([[0,0,1,0,1,0]]))
print(knn.predict([[0,0,0,0,0,0]]))
print(knn.predict([[1,1,1,1,1,1]]))

[1]
[1]
[2]
[3]
[4]
[4]
[3]
[0]
[4]


In [20]:
# confusion matrix
knncm1=confusion_matrix(y_test, y_pred)
knncm1

array([[56666,     0,     0,     0,     0],
       [    0,  1119,     0,     0,     0],
       [    0,     0,   938,     0,     0],
       [    0,     0,     0,   543,     0],
       [    0,     0,     0,     0,   590]], dtype=int64)

In [21]:
from sklearn.tree import DecisionTreeClassifier as dtc
# gini model
# -------------------------------------
# Model 1) DT with gini index criteria
clf_gini = dtc(criterion = "gini", random_state = 100, max_depth=3,
               min_samples_leaf=5).fit(X_train, y_train)
print(clf_gini)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=100)


In [22]:
from sklearn.metrics import accuracy_score, f1_score
pred_gini = clf_gini.predict(X_test)
print("Gini Accuracy is ", accuracy_score(y_test,pred_gini)*100)

Gini Accuracy is  99.25320769847634


In [23]:
# confusion matrix
cm1=confusion_matrix(y_test, pred_gini)
cm1

array([[56666,     0,     0,     0,     0],
       [    0,  1119,     0,     0,     0],
       [    0,     0,   860,     0,    78],
       [    1,   153,     0,   349,    40],
       [    0,     0,   175,     0,   415]], dtype=int64)

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(max_depth=10,random_state=101,max_features=None,min_samples_leaf=15)
dtree.fit(X_train, y_train)
y_pred_dtree=dtree.predict(X_test)
scores=metrics.accuracy_score(y_test, y_pred_dtree)
print(scores)
dtree_cm1=confusion_matrix(y_test, y_pred_dtree)
dtree_cm1

0.9999832932371023


array([[56666,     0,     0,     0,     0],
       [    0,  1119,     0,     0,     0],
       [    0,     0,   938,     0,     0],
       [    1,     0,     0,   542,     0],
       [    0,     0,     0,     0,   590]], dtype=int64)

In [25]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
rfm=RandomForestClassifier(n_estimators=70,oob_score=True,n_jobs=-1,random_state=101,max_features=None,min_samples_leaf=30)
rfm.fit(X_train, y_train)
y_pred_rfm=rfm.predict(X_test)
scores=metrics.accuracy_score(y_test, y_pred_rfm)
print(scores)
rfm_cm1=confusion_matrix(y_test, y_pred_rfm)
rfm_cm1

0.9993150227211975


array([[56666,     0,     0,     0,     0],
       [    0,  1119,     0,     0,     0],
       [    0,     0,   938,     0,     0],
       [    1,     0,     0,   502,    40],
       [    0,     0,     0,     0,   590]], dtype=int64)

In [26]:
from sklearn.svm import SVC
SVM=SVC(kernel="linear",C=0.025,random_state=101)
SVM.fit(X_train, y_train)
y_pred_SVM=SVM.predict(X_test)
scores=metrics.accuracy_score(y_test, y_pred_SVM)
print(scores)
SVM_cm1=confusion_matrix(y_test, y_pred_SVM)
SVM_cm1

1.0


array([[56666,     0,     0,     0,     0],
       [    0,  1119,     0,     0,     0],
       [    0,     0,   938,     0,     0],
       [    0,     0,     0,   543,     0],
       [    0,     0,     0,     0,   590]], dtype=int64)

### Different Methods for getting balanced dataset

**for getting balanced data set.**

1. SMOTE -- other forms of SMOTE--such as SMOTE("minority") and SMOTE(sampling_strategy=strategy)
2. ADASYN
3. SMOTETomek
4. SMOTEENN
5. RandomUnderSampler

To install imbalanced-learn library use **pip install imbalanced-learn** command

The **stratify** option in train_test_split method gives 1.0 Accuracy. Which is uses as follows:

from sklearn.model_selection import train_test_split
X_sm_train, X_sm_test, y_sm_train, y_sm_test = train_test_split(X_sm, y_sm, test_size=0.2, random_state=15, stratify=y_sm)

Where as **sometimes** without **stratify** option gives less accuracy for some balanced dataset methods. 

from sklearn.model_selection import train_test_split
X_sm_train, X_sm_test, y_sm_train, y_sm_test = train_test_split(X_sm, y_sm, test_size=0.2, random_state=15)

**The below code executes The RandomUndersampling followed by SMOTE to obtain balanced data set.**

In [27]:
#!pip install imbalanced-learn

In [28]:
from imblearn.under_sampling import RandomUnderSampler
#under = RandomUnderSampler()
under = RandomUnderSampler(sampling_strategy='majority')
X_r, y_r=under.fit_sample(X,y)
y_r.value_counts()

1    2247
2    1856
4    1232
3    1072
0    1072
Name: disease, dtype: int64

In [29]:
# RandomUnderSampler followed by either SMOTE or ADASYN
#Python code for SMOTE algorithm
from imblearn.over_sampling import SMOTE
smote=SMOTE()
X_rsm,y_rsm=smote.fit_resample(X_r,y_r)
y_rsm.value_counts()

4    2247
3    2247
2    2247
1    2247
0    2247
Name: disease, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
X_rsm_train, X_rsm_test, y_rsm_train, y_rsm_test = train_test_split(X_r, y_r, test_size=0.2, random_state=15)

In [31]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_rsm_train, y_rsm_train)
lr_y_pred=lr.predict(X_rsm_test)
scores=metrics.accuracy_score(y_rsm_test, lr_y_pred)
print(scores)
lr_cm1=confusion_matrix(y_rsm_test, lr_y_pred)
lr_cm1

1.0


array([[229,   0,   0,   0,   0],
       [  0, 448,   0,   0,   0],
       [  0,   0, 387,   0,   0],
       [  0,   0,   0, 190,   0],
       [  0,   0,   0,   0, 242]], dtype=int64)

In [32]:
#from sklearn.native_bayes import GaussianNB
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_rsm_train, y_rsm_train)
nb_y_pred=nb.predict(X_rsm_test)
scores=metrics.accuracy_score(y_rsm_test, nb_y_pred)
print(scores)
Gaussian_cm1=confusion_matrix(y_rsm_test, nb_y_pred)
Gaussian_cm1

1.0


array([[229,   0,   0,   0,   0],
       [  0, 448,   0,   0,   0],
       [  0,   0, 387,   0,   0],
       [  0,   0,   0, 190,   0],
       [  0,   0,   0,   0, 242]], dtype=int64)

In [33]:
from sklearn.linear_model import SGDClassifier
sgd=SGDClassifier(loss='modified_huber',shuffle=True,random_state=101)
sgd.fit(X_rsm_train, y_rsm_train)
y_pred_sgd=sgd.predict(X_rsm_test)
scores=metrics.accuracy_score(y_rsm_test, y_pred_sgd)
print(scores)
sgd_cm1=confusion_matrix(y_rsm_test, y_pred_sgd)
sgd_cm1

1.0


array([[229,   0,   0,   0,   0],
       [  0, 448,   0,   0,   0],
       [  0,   0, 387,   0,   0],
       [  0,   0,   0, 190,   0],
       [  0,   0,   0,   0, 242]], dtype=int64)

In [34]:
knn_rsm = KNeighborsClassifier(n_neighbors=5)
knn_rsm.fit(X_rsm_train, y_rsm_train)
y_rsm_pred = knn_rsm.predict(X_rsm_test)
scores=metrics.accuracy_score(y_rsm_test, y_rsm_pred)
print(scores)

1.0


In [35]:
# cold	cough	feaver	breating	cronic	age
print(knn.predict([[1,1,0,0,0,0]]))# Prediction of a person with some diseases.
#The output shows it is "1" Means GS,2 means HR1, 3 means HR2, and 4 means HR3.
print(knn_rsm.predict([[1,1,0,1,0,0]]))
print(knn_rsm.predict([[1,1,0,0,0,1]]))
print(knn_rsm.predict([[1,1,0,1,1,0]]))
print(knn_rsm.predict([[1,1,0,1,1,1]]))
print(knn_rsm.predict([[1,1,0,0,1,1]]))
print(knn_rsm.predict([[0,0,1,0,1,0]]))
print(knn_rsm.predict([[0,0,0,0,0,0]]))
print(knn_rsm.predict([[1,1,1,1,1,1]]))

[1]
[1]
[2]
[3]
[4]
[4]
[3]
[0]
[4]


In [36]:
knn_rsm_cm1=confusion_matrix(y_rsm_test, y_rsm_pred)
knn_rsm_cm1

array([[229,   0,   0,   0,   0],
       [  0, 448,   0,   0,   0],
       [  0,   0, 387,   0,   0],
       [  0,   0,   0, 190,   0],
       [  0,   0,   0,   0, 242]], dtype=int64)

In [37]:
# gini model
# -------------------------------------
# Model 1) DT with gini index criteria
rsm_clf_gini = dtc(criterion = "gini", random_state = 100, max_depth=3,
               min_samples_leaf=5).fit(X_rsm_train, y_rsm_train)
print(rsm_clf_gini)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=100)


In [38]:
#from sklearn.metrics import accuracy_score, f1_score
rsm_pred_gini = rsm_clf_gini.predict(X_rsm_test)
#smote_pred_gini.value_counts()
print("Gini Accuracy is ", accuracy_score(y_rsm_test,rsm_pred_gini)*100)

Gini Accuracy is  89.97326203208557


In [39]:
# confusion matrix
gini_rsm_cm1=confusion_matrix(y_rsm_test, rsm_pred_gini)
gini_rsm_cm1

array([[229,   0,   0,   0,   0],
       [150, 298,   0,   0,   0],
       [  0,   0, 387,   0,   0],
       [  0,   0,   0, 190,   0],
       [  0,   0,   0,   0, 242]], dtype=int64)

In [40]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(max_depth=10,random_state=101,max_features=None,min_samples_leaf=15)
dtree.fit(X_rsm_train, y_rsm_train)
y_pred_dtree=dtree.predict(X_rsm_test)
scores=metrics.accuracy_score(y_rsm_test, y_pred_dtree)
print(scores)
dtree_cm1=confusion_matrix(y_rsm_test, y_pred_dtree)
dtree_cm1

1.0


array([[229,   0,   0,   0,   0],
       [  0, 448,   0,   0,   0],
       [  0,   0, 387,   0,   0],
       [  0,   0,   0, 190,   0],
       [  0,   0,   0,   0, 242]], dtype=int64)

In [41]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
rfm=RandomForestClassifier(n_estimators=70,oob_score=True,n_jobs=-1,random_state=101,max_features=None,min_samples_leaf=30)
rfm.fit(X_rsm_train, y_rsm_train)
y_pred_rfm=rfm.predict(X_rsm_test)
scores=metrics.accuracy_score(y_rsm_test, y_pred_rfm)
print(scores)
rfm_cm1=confusion_matrix(y_rsm_test, y_pred_rfm)
rfm_cm1

1.0


array([[229,   0,   0,   0,   0],
       [  0, 448,   0,   0,   0],
       [  0,   0, 387,   0,   0],
       [  0,   0,   0, 190,   0],
       [  0,   0,   0,   0, 242]], dtype=int64)

In [42]:
from sklearn.svm import SVC
SVM=SVC(kernel="linear",C=0.025,random_state=101)
SVM.fit(X_rsm_train, y_rsm_train)
y_pred_SVM=SVM.predict(X_rsm_test)
scores=metrics.accuracy_score(y_rsm_test, y_pred_SVM)
print(scores)
SVM_cm1=confusion_matrix(y_rsm_test, y_pred_SVM)
SVM_cm1

1.0


array([[229,   0,   0,   0,   0],
       [  0, 448,   0,   0,   0],
       [  0,   0, 387,   0,   0],
       [  0,   0,   0, 190,   0],
       [  0,   0,   0,   0, 242]], dtype=int64)

In [43]:
# https://analyticsindiamag.com/7-types-classification-algorithms/

In [26]:
#Function to convert Decimal number
# to Binary number
def decimal_To_Binary(n):
    return bin(n).replace("0b","")
# Driver code
if __name__ == '__main__':
    print(decimal_To_Binary(7))
    print(decimal_To_Binary(9))
    print(decimal_To_Binary(10))

111
1001
1010


In [36]:
def decimal_To_Binary(n):
    b=bin(n).replace("0b","")
    if n==0:
        return int(b[0]),0,0
    elif n==1:
        return 0,0,int(b[0])
    elif n==2:
        return 0,int(b[0]),int(b[1])
    elif n==3:
        return 0,int(b[0]),int(b[1])
    else:
        return int(b[0]),int(b[1]),int(b[2])
    
    
x,y,z=decimal_To_Binary(8)
print(x,y,z)

1 0 0


In [8]:
def dectoOct(decimal):
    if(decimal > 0):
        dectoOct((int)(decimal/8))
        print(decimal%8, end='')
        
decimal = int(input("Enter a decimal number \n"))
print("Octal: ", end='')
dectoOct(decimal);

Enter a decimal number 
7
Octal: 7

In [33]:
bin(4)

'0b100'